### ISSUE TITLE
Continue training

### ISSUE THREAD

**Issue by mouxinyue1** [Zxl19990529/UGAN-pytorch#1]
hello，My program is interrupted in the middle of the course. What should I do if I want to continue my training?

**Comment by Zxl19990529** [comment]
Sorry, I did not implement the resume code. But  you can refer to ```eval_one.py``` to implement your resume code. For example:
Suppose that you have saved checkpoints ```checkpoints/netG.pth``` and ```checkpoints/netD.pth```, in your main code should have:
```py
netG.load_state_dict('checkpoints/netG.pth')
netD.load_stat_dict('checkpoints/netD.pth')
```
load the checkpoints before continue training.

**Comment by mouxinyue1** [comment]
OK，thank you for your help
